name: GH Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: bazel-contrib/setup-bazel@0.9.1
              with:
                bazelisk-cache: true
                disk-cache: ${{ github.workflow }}
                repository-cache: true
            - name: Bazel test
              run: |
                gpg --import examples/release_with_secrets/pgp/sops_functional_tests_key.asc
                bazel test //... --config=ci
            - name: Prepare release
              run: .github/workflows/release-gen.sh ${{ env.GITHUB_REF_NAME }} ${{ env.GITHUB_REPOSITORY }} > release_notes.txt
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  generate_release_notes: true
                  body_path: release_notes.txt
                  files: masorange_rules_helm-*.tar.gz
                  fail_on_unmatched_files: true
